services:
  mongo:
    image: mongo:latest
    container_name: mongodb_middleware
    restart: always
    ports:
      - '28018:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: inesPrime
      MONGO_INITDB_ROOT_PASSWORD: lesinesdufonddelaclasse
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data:
